name = "gdp"
license = "PDDL-1.0"
keywords = [ "GDP", "World", "Gross Domestic Product", "Time series"]
period = [1993, 2005]
frequency = "monthly"
category= "Economic Sectors"
maintainer = "Small Media Foundation"

[author]
name = "World Bank Group"
web = "http://worldbank.org"

[[title]]
lang = "en"
text = "Country, Regional and World GDP (Gross Domestic Product)"

[[title]]
lang = "fa"
text = "Country, Regional and World GDP (Gross Domestic Product)"

[[description]]
lang = "fa"
text = "Country, regional and world GDP in current US Dollars ($). Regional means collections of countries e.g. Europe & Central Asia. Data is sourced from the World Bank and turned into a standard normalized CSV."

[[description]]
lang = "en"
text = "Country, regional and world GDP in current US Dollars ($). Regional means collections of countries e.g. Europe & Central Asia. Data is sourced from the World Bank and turned into a standard normalized CSV."


[[resources]]

  url = "https://raw.github.com/datasets/gdp/master/data/gdp.csv"
  name = "gdp"

  [[resources.title]]
  lang = "en"
  text = "Country, Regional and World GDP (Gross Domestic Product)"

  [[resources.title]]
  lang = "fa"
  text = "Country, Regional and World GDP (Gross Domestic Product)"

  [[resources.sources]]
  name = "World Bank and OECD"
  web = "http://data.worldbank.org/indicator/NY.GDP.MKTP.CD"

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Country Name"
      type = "string"

      [[resources.schema.fields]]
      name = "Country Code"
      type = "string"

      [[resources.schema.fields]]
      name = "Year"
      type = "date"

      [[resources.schema.fields]]
      name = "Value"
      type = "number"
