name = "mhmelih16"
license = "CC-BY-NC"
keywords = [ "hospital", "Iran", "list", "health"]
period = [1392, 1392]
frequency = "yearly"
category= "Health Sector Performance"
maintainer = "Small Media Foundation"

[author]
name = "Ministry of Health and Medical Education"
web = "http://www.behdasht.gov.ir/"

[[title]]
lang = "en"
text = "Hospitals in Iran"

[[title]]
lang = "fa"
text = "لیست بیمارستان‌های ایران"

[[description]]
lang = "fa"
text = ".لیست بیمارستان‌های ایران به تفکیک شهری و استانی، آدرس و شماره تلفن "

[[description]]
lang = "en"
text = "An index of Iranian hospitals. This dataset is disaggregated by province and city, and hospitals are listed with their address and telephone number as well as their specialty, capacity."


[[resources]]

  url = "http://iod.dataset.s3.amazonaws.com/mhmellih16/mhmellih16.csv"
  name = "mhmelih16"

  [[resources.title]]
  lang = "en"
  text = "List of Iran's hospitals"

  [[resources.title]]
  lang = "fa"
  text = "لیست بیمارستان‌های ایران"

  [[resources.sources]]
  name = "World Bank and OECD"
  web = "http://data.worldbank.org/indicator/NY.GDP.MKTP.CD"

  [resources.schema]
  format = "csv"

      [[resources.schema.fields]]
      name = "Country Name"
      type = "string"

      [[resources.schema.fields]]
      name = "Country Code"
      type = "string"

      [[resources.schema.fields]]
      name = "Year"
      type = "date"

      [[resources.schema.fields]]
      name = "Value"
      type = "number"
