name = "mhmelih16"
license = "CC-BY-NC"
keywords = [ "hospital", "Iran", "list", "health"]
period = [1392, 1392]
frequency = "yearly"
category= "Health Sector Performance"
maintainer = "Small Media Foundation"

[author]
name = "Ministry of Health and Medical Education"
web = "http://www.behdasht.gov.ir/"

[[title]]
lang = "en"
text = "List of Iran's hospitals"

[[title]]
lang = "fa"
text = "لیست بیمارستان‌های ایران"

[[description]]
lang = "fa"
text = ".لیست بیمارستان‌های ایران به تفکیک شهری و استانی، آدرس و شماره تلفن "

[[description]]
lang = "en"
text = "The list of the hospitals in Iran, disaggregated by province and cities with their address and telephone number."


[[resources]]

  url = "https://iod.dataset.s3.amazonaws.com/mhmellih16/mhmellih16.csv"
  name = "mhmelih16"
  code = "https://github.com/iranopendata/ingest/blob/master/ruby/mhmellih16.rb"

  [[resources.title]]
  lang = "en"
  text = "List of Iran's hospitals"

  [[resources.title]]
  lang = "fa"
  text = "لیست بیمارستان‌های ایران"

  [[resources.sources]]
  name = "World Bank and OECD"
  web = "http://data.worldbank.org/indicator/NY.GDP.MKTP.CD"

  [resources.schema]
  format = "csv"

     [[resources.schema.fields]] 
     name = "name"
     typr = "string"

     [[resources.schema.fields]] 
     name = "city"
     typr = "string"

     [[resources.schema.fields]] 
     name = "address"
     typr = "string"

     [[resources.schema.fields]] 
     name = "tel"
     typr = "string"

     [[resources.schema.fields]] 
     name = "soc_id"
     typr = "string"

     [[resources.schema.fields]] 
     name = "hsp_type"
     typr = "string"

     [[resources.schema.fields]] 
     name = "bed_count"
     typr = "string"

     [[resources.schema.fields]] 
     name = "spc_type"
     typr = "string"

     [[resources.schema.fields]] 
     name = "ward1"
     typr = "string"

     [[resources.schema.fields]] 
     name = "ward2"
     typr = "string"

     [[resources.schema.fields]] 
     name = "ward3"
     typr = "string"

     [[resources.schema.fields]] 
     name = "ward4"
     typr = "string"

     [[resources.schema.fields]] 
     name = "email"
     typr = "string"

